/* Nazwa
*  Membuat tabel utama
*  Authored by Deri Herdianto
*  c 2020
*/

-- Tabel role/peran
CREATE TABLE "role" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);

-- Buat peran
INSERT INTO "role" ("id", "name")
VALUES  (1, 'admin'),
        (2, 'surveyor'),
        (3, 'collector'),
        (4, 'sales'),
        (5, 'customer');

-- Buat gender
CREATE TYPE "gender" AS ENUM ('f', 'm');

-- Tabel user/pengguna
CREATE TABLE "user" (
    "id" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "first_name" VARCHAR(25) NOT NULL,
    "last_name" VARCHAR(25),
    "username" VARCHAR(25) UNIQUE,
    "avatar" VARCHAR(25) DEFAULT 'default.jpg',
    "password" CHAR(60),
    "gender" GENDER NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "balance" DECIMAL(15,2) DEFAULT '0',
    PRIMARY KEY (id)
);

-- Tabel peran user/pengguna
CREATE TABLE "user_role" (
    "id" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "role_id" INT NOT NULL,
    "user_id" INT UNIQUE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES "role"("id"),
    FOREIGN KEY (user_id) REFERENCES "user"("id")
);

-- Tabel email
-- Pengguna boleh memiliki beberapa email
CREATE TABLE "email" (
    "id" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" INT NOT NULL,
    "email" VARCHAR(60) UNIQUE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES "user"("id")
);

-- Tabel nomor HP
-- Pengguna boleh memiliki lebih dari satu nomor HP
CREATE TABLE "phone" (
    "id" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "user_id" INT NOT NULL,
    "phone" VARCHAR(15) UNIQUE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES "user"("id")
);

-- Tabel provinsi
CREATE TABLE "province" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "parent" INT NOT NULL,
    "name" VARCHAR (50) NOT NULL,
    "deault" BOOLEAN DEFAULT 'true' NOT NULL,
    PRIMARY KEY (id)
);